### ISSUE TITLE
Terminal Color

### ISSUE THREAD

**Issue by dadajonovich** [DaKili/oxocarbon-5#1]
Hi, thanks for the lovely theme! Could you refine the colors inside the terminal? Without them, the topic looks unfinished.

**Comment by DaKili** [comment]
Hi,
I'm currently trying to add the light theme and refine the current one a little (adding stuff i missed on my first iteration).
[Terminal colors should however be in place](https://github.com/DaKili/oxocarbon-5/blob/0ba796dac58bc7d6f9a461f1d39b9644117b0a2a/themes/oxocarbon-5-color-theme.json#L219C3-L219C4
).
Can you provide me with a screenshot of what you mean?

**Comment by dadajonovich** [comment]
Sorry for the long answer. I meant the colors in the terminal block (see screenshot). Unfortunately, I can't tell you what they are called in the json schema
![Снимок экрана от 2024-09-12 11-00-46](https://github.com/user-attachments/assets/09a12a6a-5941-4de4-90ae-ef4d1d9011f8)

**Comment by DaKili** [comment]
I did some testing and the terminal colors from my previous link are actually loaded by the theme properly.
I'm not completely sure how they are loaded, but I can only influence the 16 colors like "terminal.ansiBrightGreen". Then whenever VSCode thinks the original color is bright green, it loads the bright green color I gave it.

The issue is, that the original oxocarbon.nvim theme does only have one green "#42be65", which the original also loads very rarely. For bright green I tried to come up with one that somewhat fits the style of the original theme. But I agree, that the color sucks, since oxocarbon is not really meant to use green colors.

4 Solutions come to my mind:
- **Change colors like "terminal.brightGreen" to something that is actually purple.** This is what you are indirectly are suggesting. This would however override the output of every program executed in the terminal as well. Every output that people are used to being bright green would then be purple, so I don't like this option.
- **Find better colors for the ansi terminal colors.** That could make the most sense, but I don't know color theory (which is why the current colors suck), or at least spend a lot of time finding optimal colors, but I don't have time to learn it right now.
- **Workaround: Override the themes colors in the settings.json** like in [this StackOverflow post](https://stackoverflow.com/questions/42307949/color-theme-for-vs-code-integrated-terminal)
- **Change the PROMPT in the .bashrc** to something fitting to oxocarbon like: PS1="\[\e[38;5;110m\]\u\[\e[0m\]@\[\e[38;5;33m\]\h\[\e[0m\]:\[\e[38;5;105m\]\w\[\e[0m\]\[\e[38;5;8m\]\\$\[\e[0m\] " for this: 
![Visual Studio Code](https://github.com/user-attachments/assets/2cc5e518-4e2b-4b57-bbe5-2401145815bb)

Hope this helps. If you have another idea feel free to let me know.
